#' Take a subset from the flowSet
#'
#' @param fsom FlowSOM object as generated by the FlowSOM function
#' @param file File to select
#'
#' @export
FlowSOM_subset <- function(fsom, file){
  fsom_selected <- FlowSOMSubset(fsom$FlowSOM,
                                 fsom$FlowSOM$metaData[[file]][1]:fsom$FlowSOM$metaData[[file]][2])
  return(list(FlowSOM = fsom_selected, metaclustering = fsom$metaclustering))
}
